### ISSUE TITLE
bug: download button on website is broken

### ISSUE THREAD

**Issue by tomsquest** [geek-fun/dockit#41]
Hi,

On DocKit website, the download button is not working.
I think the error comes from:

```
TypeError: navigator.userAgentData is undefined
    n https://dockit.geekfun.club/assets/chunks/theme.lK2rZp0k.js:1
    Ge https://dockit.geekfun.club/assets/chunks/framework.PNMSvVW_.js:1
    Se https://dockit.geekfun.club/assets/chunks/framework.PNMSvVW_.js:1
    n https://dockit.geekfun.club/assets/chunks/framework.PNMSvVW_.js:1
```

![image](https://github.com/geek-fun/dockit/assets/365778/fc1e9817-5256-47d4-889a-442d2a6f3fa4)

**Comment by tomsquest** [comment]
Hi @Blankll 

Pretty sure it is being blocked by Firefox privacy settings.

I am using 124.0.1 (64-bit) on Ubuntu, ublock, tracking protection in `strict` mode.

**Comment by Blankll** [comment]
Thanks, I'll have a look

**Comment by Blankll** [comment]
the function to detect host arch and OS is supported only by limited browsers,  btw I have added auto-new version detect to directly download the latest version instead of visiting the browser again, this issue should be not necessary to fix then
see the support list: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData

**Comment by tomsquest** [comment]
Ok.

Suggestion: the Releases section of Github could be fallback if the download code failed to execute.
